filter:
    excluded_paths: [doc/*, examples/*, tests/*]

checks:
    php: true

build:
    dependencies:
        before:
            - mysql -uroot -e 'CREATE DATABASE phpunit_icsmunger'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
        tests-and-coverage:
            services:
                mysql: "5.7"
            tests:
                override:
                    - command: vendor/bin/phpunit --coverage-clover=coverage.clover
                      coverage:
                          file: coverage.clover
                          format: clover
